pipeline {
    agent {
        node{
            label 'AGENT-1'
        }
    }
    environment {
        GREETING = 'Hello Jenkins'
    }
    options{
        // timeout(time:1,unit:'HOURS')
        // disableConcurrentBuilds()
         ansiColor('xterm')
    }

    parameter {
          choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    
//build
    stages {
        stage('INIT') {
            steps {
                sh """
                    cd 01-vpc
                    terraform init -reconfigure
                   """ 

                 
            }
        }
        stage('plan') {
            steps {
                sh """
                    cd 01-vpc
                    terraform plan
                   """ 
            }
        }
        stage('Deploy') {
            when {
                expression {
                    params.action =='apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            steps {
                sh"""
                   cd 01-vpc
                    terraform apply -auto-approve
                
                """
            }
        }
        
    }

    //post build
    post {
        always{
            echo 'I willalways say Hello again!'
        }
        failure{
            echo 'this runs when pipeline is failed, used generally to send some alerts'
        }
        success{
            echo ' i say Hello pipeline is successs'
        }
    }
}

